Description: Ejemplo de Webserver usando EC2, instala apache y crea una pagina index de ejemplo.
Parameters:
  AMI:
    Description: Amazon Machine Image para la instancia EC2
    Type: String
  Region:
    Description: Region para el index.
    Type: String
  Background:
    Description: Background para el index.
    Type: String

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Habilitar el puerto 80
      GroupName: !Sub utilapis-sg-${Region}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: !Sub WebServer-${Region}
      ImageId: !Sub ${AMI}
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: WebServerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install httpd -y
          echo '<html><body style="background: ${Background};"><h1>Hola Utilapis desde ${Region}!!</h1></body></html>' > /var/www/html/index.html
          service httpd start
          chkconfig httpd on

Outputs:
  InstanceId:
    Description: EC2 InstanceId del WebServer
    Value:
      Ref: WebServerHost
  WebsiteURL:
    Description: Index del WebServer
    Value: !Sub http://${WebServerHost.PublicDnsName}/index.html
  PublicIP:
    Description: IP publica del WebServer
    Value: !GetAtt WebServerHost.PublicIp
    Export:
      Name: !Sub ${AWS::StackName}-WebServerHost-IP
